# Generated by Django 4.1 on 2022-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learnPython", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
